Bookstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # Django admin
    path("admin/", admin.site.urls),
    # Third Party apps urls
    path("social-auth/", include("allauth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    # Local apps
    path("accounts/", include("accounts.urls")),
    path("profile/", include("users.urls")),
    path("", include("books.urls")),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

books/urls.py
from django.urls import path

from .views import (
    HomePageView,
    BookDetailView,
    AboutPageView,
    ContactPageView,
    NewsLetterView,
    ReviewView,
    BooksByAuthorView,
    AddBookView,
    AllBooksView,
    UpdateBookView,
    DeleteBookView,
    AllProductsView,
    SearchView,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("books/add-book/", AddBookView.as_view(), name="add_book"),
    path("books/all-books/", AllBooksView.as_view(), name="all_books"),
    path("books/all-products/", AllProductsView.as_view(), name="all_products"),
    path("books/search/", SearchView.as_view(), name="book_search_results"),
    path("books/update-book/<slug:slug>/", UpdateBookView.as_view(), name="update_book"),
    path("books/delete-book/<slug:slug>/", DeleteBookView.as_view(), name="delete_book"),
    path("books/detail/<slug:slug>/", BookDetailView.as_view(), name="book_detail"),
    path("books/about/", AboutPageView.as_view(), name="about"),
    path("books/contact/", ContactPageView.as_view(), name="contact"),
    path("books/newsletter/", NewsLetterView.as_view(), name="newsletter"),
    path("books/review/", ReviewView.as_view(), name="review"),
    path("books/<str:author_name>/", BooksByAuthorView.as_view(), name="author_books"),
]

users/urls.py
from django.urls import path
from .views import MyProfile

app_name = "users"

urlpatterns = [
    # Users Profile
    path("", MyProfile.as_view(), name="profile"),
]

templates/booksaw/header/header.html
{% load static %}
{% load socialaccount %}
<div id="header-wrap">
    <div class="top-content">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="social-links">
                        <ul>
                            <li>
                                <a href="{% provider_login_url 'github' %}">
                                <i class="fab fa-github"></i></a>
                            </li>
                            <li>
                                <a href="{% provider_login_url 'twitter' %}">
                                    <i class="fab fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="{% provider_login_url 'google' %}">
                                    <i class="fab fa-google"></i></a>
                            </li>
                        </ul>
                    </div>
                    <!--social-links-->
                </div>
                <div class="col-md-9">
                    <div class="right-element">
                        <div class="main-menu stellarnav">
                            <ul class="menu-list">
                                <a href="#" class="cart for-buy">
                                    <i class="icon icon-clipboard"></i>
                                    <span>Cart:(0 $)</span>
                                </a>
                                <div class="action-menu">
                                    <div class="search-bar">
                                        <a href="{% url 'book_search_results' %}"
                                           class="search-button search-toggle"
                                           data-selector="#header-wrap">
                                            <i class="icon icon-search"></i>
                                        </a>
                                        <form action="{% url 'book_search_results' %}"
                                              role="search" method="get"
                                              class="search-box">
                                            <input class="search-field text search-input"
                                                   placeholder="Search"
                                                   type="search"
                                                   name="query"
                                                   aria-label="Search">
                                        </form>
                                    </div>
                                </div>
                                {% if user.is_authenticated %}
                                <li class="menu-item has-sub">
                                    <a href="#user" class="nav-link" data-effect="User">
                                        {{ user.username }}
                                    </a>
                                    <ul>
                                        <li class="active">
                                            <a href="{% url 'users:profile' %}" class="user-account for-buy">
                                                <i class="icon icon-user"></i>
                                                <span>Profile</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'logout' %}" class="user-account for-buy">
                                                <i class="fas fa-sign-out-alt"></i>
                                                <span>LogOut</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'password_change' %}">
                                                <span>Change Password</span>
                                            </a>
                                        </li>
                                        {% if user.is_superuser %}
                                        <li>
                                            <a href="{% url 'add_book' %}">
                                                <span>Add Book</span>
                                            </a>
                                        </li>
                                        
                                            <a href="{% url 'all_books' %}">
                                                <span>All Books</span>
                                            </a>
                                        </li>
                                        {% endif %}                          
                                    </ul>
                                </li>
                                {% else %}
                                    <a href="{% url 'login' %}" class="user-account for-buy">
                                        <i class="fas fa-sign-in-alt"></i>
                                        <span>LogIn</span>
                                    </a>
                                    <a href="{% url 'signup' %}" class="user-account for-buy">
                                        <i class="icon icon-user"></i>
                                        <span>SignUp</span>
                                    </a>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <!--top-right-->
                </div>
            </div>
        </div>
    </div>
    <!--top-content-->
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="main-logo">
                        <a href="{% url 'home' %}">
                            <img src="{% static 'booksaw/images/main-logo.png' %}" alt="logo" />
                        </a>
                    </div>
                </div>
                <div class="col-md-10">
                    <nav id="navbar">
                        <div class="main-menu stellarnav">
                            <ul class="menu-list">
                                <li class="menu-item active">
                                    <a href="{% url 'home' %}" data-effect="Home">Home</a>
                                </li>
                                <li class="menu-item">
                                    <a href="{% url 'about' %}" class="nav-link" data-effect="About">About</a>
                                </li>
                                <li class="menu-item">
                                    <a href="{% url 'all_products' %}" class="nav-link" data-effect="Shop">Shop</a>
                                </li>
                                <li class="menu-item">
                                    <a href="{% url 'contact' %}" class="nav-link" data-effect="Contact">Contact</a>
                                </li>
                            </ul>
                            <div class="hamburger">
                                <span class="bar"></span>
                                <span class="bar"></span>
                                <span class="bar"></span>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
</div>
<!--header-wrap-->